apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: devankit2022/devankit-faundadb-api:0.0.2.RELEASE
          env:
            - name: FAUNA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: api-token
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
